### ISSUE TITLE
let's pick a license

### ISSUE THREAD

**Issue by rabernat** [rabernat/research_computing#1]
@kerrykey: now that our course material is going online, we should pick an appropriate license.

I propose we license the material under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode)

I reached this by following this guide: https://creativecommons.org/choose

If you agree, I will add a license file to the repo.

**Comment by rabernat** [comment]
Maybe we should make it a non-commercial license.

**Comment by kerrykey** [comment]
Sounds good. Let's go with the non-commercial version.
